### ISSUE TITLE
Character `-` not recognized

### ISSUE THREAD

**Issue by Kanro-Code** [not-an-aardvark/reddit-oauth-helper#1]
When copy/pasting a client secret with a dash, reddit-oauth-helper does not function.
After creating several apps on reddit and finally getting a secret without a dash, the program worked just fine.

```
Please enter your client secret. This is the 27-character string that appears when you click "edit" next to your 
app on this page: https://www.reddit.com/prefs/apps
```

**Comment by not-an-aardvark** [comment]
TIL that dashes are legal characters in client IDs/secrets.

Anyway, thanks for the report; I just pushed v0.2.3 which should fix this.
