### ISSUE TITLE
imported package open 0.0.5 is vulnerable to Command Injection

### ISSUE THREAD

**Issue by ghost** [not-an-aardvark/reddit-oauth-helper#11]
installing reddit-oauth-helper via npm will raise:  
`found 1 critical severity vulnerability`  

This is because of open, according to https://www.npmjs.com/advisories/663.

> Versions of open before 6.0.0 are vulnerable to command injection when unsanitized user input is passed in.

**Comment by not-an-aardvark** [comment]
Thanks for the report. This package is not affected by the vulnerability, but I'd be happy to review a PR if you're interested in upgrading the dependency.
