### ISSUE TITLE
Can't generate permanent tokens

### ISSUE THREAD

**Issue by TravelingTechGuy** [not-an-aardvark/reddit-oauth-helper#16]
I'm trying to generate a permanent token for my app, so I can put it in an `.env` file,. and move on to the logic :)

The only permission I need is "read". Regardless of whether I mark the permanent check box on `https://not-an-aardvark.github.io/reddit-oauth-helper/` or not, the response comes back with a token limited to an hour. I've tried everything - it always comes back with:

```
{
  access_token: "number-string"
  token_type: "bearer"
  expires_in: "3600"                     <-- culprit
  scope: "read"
}
```

I tried using the command line version (with `npx`): changed the redirect_uri for my app, ran the command line, and got the exact same result. It ends up generating this URL:

`https://www.reddit.com/api/v1/authorize?client_id=myclientid&response_type=code&state=somestring%2Bkg%3D%3D&redirect_uri=http%3A%2F%2Flocalhost%3A65010%2Fauthorize_callback&duration=permanent&scope=read`

The problem is, after a token expires, snoowrap fails in spectacular ways (returning HTML instead of Listings object etc.), so I must have a permanent token.

Is it something to do with Reddit itself? My app? Something in the code?

Thanks!

**Comment by not-an-aardvark** [comment]
When you check the "permanent" checkbox, does the response have an additional `refresh_token` field? If you want a permanent token, you should always use the `refresh_token` rather than the `access_token`.

**Comment by TravelingTechGuy** [comment]
I do get a refresh_token back. But if I only try to use the `refreshToken` in the credentials, it errors and asks to `accessToken` as well (which times out after an hour).

**Comment by not-an-aardvark** [comment]
> it errors and asks to accessToken as well

What is the error message?

**Comment by TravelingTechGuy** [comment]
I think I'm starting to see **my error**: I think I kept passing bot accessToken and refreshToken to the constructor, when all I needed to pass was ***just*** the refreshToken?

Is only the accessToken expiring after 3600 seconds?

**Comment by not-an-aardvark** [comment]
The refresh token does not expire.
