### ISSUE TITLE
CLI requires Client ID be 14 characters 

### ISSUE THREAD

**Issue by pennro-se** [not-an-aardvark/reddit-oauth-helper#22]
Hello! Thanks for making this script/app, it's very useful.

When I tried to get a token via the CLI, I got stuck trying to submit a Client ID as it was checking for a 14 character string when my Client ID is 22 characters long.

However when I switched to using your hosted web interface, I was able to use my Client ID without issue.

I don't know if the fix is as simple as removing the length limitation so I'll leave this as an issue and not a PR.

Thanks again!

**Comment by ralyodio** [comment]
neither worked for me.

**Comment by not-an-aardvark** [comment]
Hi, sorry about the delayed reply. I think it would make sense to just remove the length limit in the CLI, since reddit changed how it generates the IDs and it might change it again in the future. I'd be happy to accept a PR.

**Comment by aeharding** [comment]
Any chance we could get a release cut and pushed to npm? Thanks for your work on this project.

**Comment by not-an-aardvark** [comment]
Published as v0.3.2, thanks for the reminder.
