### ISSUE TITLE
Bad Request Error

### ISSUE THREAD

**Issue by neelgeek** [not-an-aardvark/reddit-oauth-helper#6]
![image](https://user-images.githubusercontent.com/23404202/49738182-bffad600-fcb4-11e8-82c0-7db1cc8b5568.png)
I was trying to create a token for a script.
However, after selecting all options, it link which is generated, shows "Bad Request."
![image](https://user-images.githubusercontent.com/23404202/49738289-08b28f00-fcb5-11e8-8885-2bb14d484058.png)

**Comment by jampod-dev** [comment]
You need to set the redirect URI in your app's preferences to:

`http://localhost:65010/authorize_callback`
