### ISSUE TITLE
Add "copy to clipboard" button to the generated tokens in the webview

### ISSUE THREAD

**Issue by TimJentzsch** [not-an-aardvark/reddit-oauth-helper#8]
This would make it easier to use the generated tokens.

**Comment by not-an-aardvark** [comment]
Seems reasonable to me. Would you like to submit a pull request?

**Comment by TimJentzsch** [comment]
Sure, haven't really worked with React yet, but I can try.

**Comment by 0xkarambit** [comment]
hey @not-an-aardvark , @TimJentzsch is it cool if i do the pull request to add the button ?

**Comment by TimJentzsch** [comment]
Sure, fine from my side
